version: '1.0'

services:
  django-db:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
    networks:
      - djangonetwork
  django-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./django_xss_scanner/:/usr/src/app/:consistent
    ports:
      - 8000:8000
    command : python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    depends_on:
      - django-db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_data: